### ISSUE TITLE
UITextField's delegate don't need to set?

### ISSUE THREAD

**Issue by hengchengfei** [michalkonturek/KeyboardController#2]
if i don't set the textfield's delegate,the textfield's delegate don't go into.
self.xxTextField.delegate = self;

#pragma mark -
#pragma mark Text Field Delegate

- (void)textFieldDidBeginEditing:(UITextField *)textField
{
    [self.keyboardControls setActiveField:textField];
}

**Comment by michalkonturek** [comment]
I am not sure what you mean. Could you rephrase it please?
